### ISSUE TITLE
Problem with pyblocxs and ciao 4.10

### ISSUE THREAD

**Issue by rhysaph** [astrostat/pyblocxs#2]
Hi,

I have initialised ciao and set the PYTHONPATH variable to point to the unzipped yblocxs-master directory but it refuses to load into python, see below. Is this a python 2 vs python 3 issue?

Thanks for any help,
Rhys Morris

source /usr/local/ciao64/ciao-4.10/bin/ciao.bash
CIAO configuration is complete... 
CIAO 4.10 Thursday, April 12, 2018
  bindir      : /usr/local/ciao64/ciao-4.10/bin
  CALDB       : 4.7.9

which python
/usr/local/ciao64/ciao-4.10/bin/python

 export PYTHONPATH=/usersc/phrahm/pyblocxs-master

 python
Python 3.5.4 (default, Oct 25 2017, 15:37:39) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyblocxs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usersc/phrahm/pyblocxs-master/pyblocxs.py", line 1, in <module>
    from ui import *
  File "/usersc/phrahm/pyblocxs-master/ui.py", line 35
    raise RuntimeError, "No fit results available!"
                      ^
SyntaxError: invalid syntax

**Comment by vkashyap** [comment]
Hi,

Yes, very likely a python 2 vs 3 problem.  Thanks for flagging it, we will look into fixing it.  In the meantime, pyblocxs is available as part of CIAO as the tool "get_draws".  It has all the functionality of this version except for the fullBayes analysis of calibration uncertainty.

Vinay
